spring:
  application:
    name: spring-boot-kafka
  main:
    banner-mode: off

spring-boot-kafka:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL:localhost}:9092
    group-id: order
    topics:
      create-order: create-order

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
