#Service fiel to expose kafka outside kafka namespace
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: default
spec:
  type: ExternalName
  externalName: kafka-service.kafka.svc.cluster.local
  ports:
    - port: 9092
      targetPort: 9092
---

# service file
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
  labels:
    app: kafka-broker
spec:
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka-broker

---
#Deployment file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
  namespace: kafka
  labels:
    app: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      name: kafka-broker
      namespace: kafka
      labels:
        app: kafka-broker
    spec:
      containers:
        - name: kafka-broker
          image: confluentinc/cp-kafka:7.3.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-service:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LOG4J_LOGGERS
              value: "name: kafka.controller=INFO,name: kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_AUTHORIZER_CLASS_NAME
              value: "kafka.security.authorizer.AclAuthorizer"
            - name: KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND
              value: "true"