apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
  labels:
    app: kafka-broker
spec:
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka-broker