apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: kafka
  labels:
    app: zookeeper-service
spec:
  type: NodePort
  port:
    - protocol: TCP
      port: 2181
  selector:
    app: zookeeper





